spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ingreedy}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ingreedy}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ingreedy}
